application: pt-cam
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/?$

  static_files: static/index.html
  upload: static/index\.html

- url: /components
  static_dir: components

- url: /
  static_files: static/index.html
  upload: static/index\.html
